#!/usr/bin/env bash
set -eu

echo "🔵 pre_build"
#source hooks/.config

echo "✅ Register qemu-*-static for all supported processors except current"
echo "⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯"



cat < EOF >> start.sh
apk add bash go make git gnupg musl-dev openssl util-linux tar
git clone https://github.com/NetApp/trident
export GOARCH=ppc64le
export GOOS=linux
makefiles modification....
cd trident
sed -i 's/^GO_LINUX = ${DR_LINUX} ${GO_CMD}/GO_LINUX = \$\{GO_CMD\}/' Makefile
sed -i 's/^TRIDENT_VOLUME_PATH = \/go\/src\/github.com\/netapp\/trident/TRIDENT_VOLUME_PATH = ${ROOT}/' Makefile
sed -i 's/docker build/docker buildx build --platform linux\/ppc64le/' Makefile
make trident_build
EOF

chmod 777 start.sh

docker run -it --rm -v "$(pwd)/":/data/ jdrouet/docker-with-buildx:stable /data/start.sh


docker images